## Linearity

In [1]:
from scipy import stats
stock_returns=[0.065,0.0265,-0.0593,-0.001,0.0346]
mkt_returns=[0.055,-0.09,-0.041,0.045,0.022]
beta,alpha,r_value,p_value,std_err=stats.linregress(stock_returns,mkt_returns)

In [2]:
print(beta,alpha)

0.5077431878770808 -0.008481900352462384


## OLS

In [4]:
## ols
import numpy as np
import statsmodels.api as sm
num_periods=9
all_values=np.array([np.random.random(8) for i in range(num_periods)])
y_values=all_values[:,0]
x_values=all_values[:,1:]
x_values=sm.add_constant(x_values)
results=sm.OLS(y_values,x_values).fit()

In [5]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.925
Model:                            OLS   Adj. R-squared:                  0.398
Method:                 Least Squares   F-statistic:                     1.756
Date:                Sat, 20 Feb 2021   Prob (F-statistic):              0.525
Time:                        15:54:33   Log-Likelihood:                 11.309
No. Observations:                   9   AIC:                            -6.619
Df Residuals:                       1   BIC:                            -5.041
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.1475      1.900     -1.656      0.3

C:\Users\16469\anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [6]:
print(results.params)

[-3.14746448 -0.07028753  3.06702871  0.38126497  2.25910553  0.45111968
  0.48668399  2.41276872]


In [7]:
import pulp
x=pulp.LpVariable('x',lowBound=0)
y=pulp.LpVariable('y',lowBound=0)
problem=pulp.LpProblem('A simple max opjective',pulp.LpMaximize)
problem+=3*x+2*y,'objective function'
problem+=2*x+y<=100,'1st constraint'
problem+=x+y<=80,'2nd constraint'
problem+=x<=40,'3rd constraint'
problem.solve()

C:\Users\16469\anaconda3\lib\site-packages\pulp\pulp.py:1199: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


1

In [8]:
print('Max Results:')
for variable in problem.variables():
    print(variable.name,'=',variable.varValue)

Max Results:
x = 20.0
y = 60.0


In [9]:
import pulp
dealers=['X','Y','Z']
variable_costs={'X':500,'Y':350,'Z':450}
fixed_costs={'X':4000,'Y':2000,'Z':6000}
quantities=pulp.LpVariable.dicts('quantity',dealers,lowBound=0,cat=pulp.LpInteger)
is_orders=pulp.LpVariable.dicts('orders',dealers,cat=pulp.LpBinary)
model=pulp.LpProblem('A min cost problem',pulp.LpMinimize)
model+=sum([variable_costs[i]*quantities[i]+fixed_costs[i]*is_orders[i] for i in dealers]),'Min portfolio cost'
model+=sum([quantities[i] for i in dealers])==150,'Total contracts required'
model+=is_orders['X']*30<=quantities['X']<=is_orders['X']*100,'Boundary of X'
model+=is_orders['Y']*30<=quantities['Y']<=is_orders['Y']*90,'Boundary of Y'
model+=is_orders['Z']*30<=quantities['Z']<=is_orders['Z']*70,'Boundary of Z'
model.solve()

1

In [10]:
print("Min results:")
for variable in model.variables():
    print(variable,'=',variable.varValue)
print('Total cost:',pulp.value(model.objective))

Min results:
orders_X = 0.0
orders_Y = 1.0
orders_Z = 1.0
quantity_X = 0.0
quantity_Y = 90.0
quantity_Z = 60.0
Total cost: 66500.0


In [12]:
import numpy as np
A=np.array([[2,1,1],[1,3,2],[1,0,0]])
B=np.array([4,5,6])
print(np.linalg.solve(A,B))

[  6.  15. -23.]


## LU

In [13]:
## LU
import scipy.linalg as linalg
A=np.array([[2,1,1],[1,3,2],[1,0,0]])
B=np.array([4,5,6])
LU=linalg.lu_factor(A)
x=linalg.lu_solve(LU, B)
print(x)

[  6.  15. -23.]


In [23]:
import scipy
A=np.array([[2,1,1],[1,3,2],[1,0,0]])
P,L,U=scipy.linalg.lu(A)
print('P=\n',P)
print('L=\n',L)
print('U=\n',U)

P=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L=
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
U=
 [[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


## Cholesky

In [24]:
## Cholesky
A=np.array([
    [10,-1,2,0],
    [-1,11,-1,3],
    [2,-1,10,-1],
    [0,3,-1,8]
])
B=np.array([6,25,-11,15])
L=np.linalg.cholesky(A)

In [25]:
print(L)

[[ 3.16227766  0.          0.          0.        ]
 [-0.31622777  3.3015148   0.          0.        ]
 [ 0.63245553 -0.24231301  3.08889696  0.        ]
 [ 0.          0.9086738  -0.25245792  2.6665665 ]]


In [26]:
print(np.dot(L,L.T.conj())) 


[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]


In [27]:
y=np.linalg.solve(L,B)

In [28]:
x=np.linalg.solve(L.T.conj(),y)
print(x)

[ 1.  2. -1.  1.]


In [29]:
print(np.mat(A)*np.mat(x).T)

[[  6.]
 [ 25.]
 [-11.]
 [ 15.]]


## QR

In [30]:
## QR
A=np.array([
    [2,1,1],
    [1,3,2],
    [1,0,0]
])
B=np.array([4,5,6])
Q,R=scipy.linalg.qr(A)
y=np.dot(Q.T,B)
x=scipy.linalg.solve(R,y)
print(x)

[  6.  15. -23.]


## Jacobi

In [32]:
## Jacobi
def jacobi(A,B,n,tol=1e-10):
    x=np.zeros_like(B)
    for iter_count in range(n):
        x_new=np.zeros_like(x)
        for i in range(A.shape[0]):
            s1=np.dot(A[i,:i],x[:i])  ##lower
            s2=np.dot(A[i,i+1:],x[i+1:]) ##upper
            x_new[i]=(B[i]-s1-s2)/A[i,i]
        if np.allclose(x,x_new,tol):
            break
        x=x_new
    return x

In [33]:
A=np.array([
    [10,-1,2,0],
    [-1,11,-1,3],
    [2,-1,10,-1],
    [0,3,-1,8]
])
B=np.array([6,25,-11,15])
n=25

In [34]:
x=jacobi(A,B,n)
print('x','=',x)

x = [ 0  2 -1  1]


## Gauss-Seidel

In [61]:
## Gauss-Seidel
def gauss(A,B,n,tol=1e-10):
    L=np.tril(A)
    U=A-L
    L_inv=np.linalg.inv(L) # compute inverse 
    x=np.zeros_like(B)
    
    for i in range(n):
        Ux=np.dot(U, x)
        x_new=np.dot(L_inv, B-Ux)
        if np.allclose(x,x_new,tol):
            break
        x=x_new
    return x

In [62]:
n=100
A=np.array([
    [10,-1,2,0],
    [-1,11,-1,3],
    [2,-1,10,-1],
    [0,3,-1,8]
])
B=np.array([6,25,-11,15])
x=gauss(A,B,n)

In [63]:
print('x','=',x)

x = [ 1.  2. -1.  1.]


## Nonlinearity: Root-finding

In [65]:
## incremental search
def incremental_search(func,a,b,dx):
    fa=func(a)
    c=a+dx
    fc=func(c)
    n=1
    while np.sign(fa)==np.sign(fc):
        if a>=b:
            return a-dx,n
        a=c
        fa=fc
        c=a+dx
        fc=func(c)
        n+=1
    if fa==0:
        return a,n
    elif fc==0:
        return c,n
    else:
        return (a+c)/2,n

In [66]:
y=lambda x:x**3+2*x**2-5
root,iterations=incremental_search(y,-5,5,0.001)
print('Root is:',root)
print('Iterations:',iterations)

Root is: 1.2414999999999783
Iterations: 6242


## Bisection

In [67]:
## bisection
def bisection(func,a,b,tol=0.1,maxiter=10):
    c=(a+b)/2
    n=1
    while n<=maxiter:
        c=(a+b)/2
        if func(c)==0 or abs(a-b)/2<tol:
            return c,n
        n+=1
        if func(c)<0:
            a=c
        else:
            b=c
    return c,n

In [68]:
y=lambda x:x**3+2*x**2-5
root,iterations=bisection(y,-5,5,0.00001,100)
print('Root is:',root)
print('Iterations:',iterations)

Root is: 1.241903305053711
Iterations: 20


## Newton's

In [69]:
## Newton's
def newton(func,df,x,tol=0.001,maxiter=100):
    n=1
    while n<=maxiter:
        x1=x-func(x)/df(x)
        if abs(x1-x)<tol:
            return x1,n
        x=x1
        n+=1
    return None,n

In [70]:
y=lambda x:x**3+2*x**2-5
dy=lambda x:3*x**2+4*x
root,iterations=newton(y,dy,5,0.00001,100)
print('Root is:',root)
print('Iterations:',iterations)

Root is: 1.241896563034502
Iterations: 7


## Secant

In [71]:
## secant
def secant(func,a,b,tol=0.001,maxiter=100):
    n=1
    while n<=maxiter:
        c=b-func(b)*((b-a)/(func(b)-func(a)))
        if abs(c-b)<=tol:
            return c,n
        a=b
        b=c
        n+=1
    return None,n

In [72]:
y=lambda x:x**3+2*x**2-5
root,iterations=secant(y,-5,5,0.00001,100)
print('Root is:',root)
print('Iterations:',iterations)

Root is: 1.2418965622558549
Iterations: 14


## Scipy built-in root-finding

In [76]:
import scipy.optimize as optimize
y=lambda x:x**3+2*x**2-5
dy=lambda x:3*x**2+4*x

print('Bisection:',optimize.bisect(y,-5,5,xtol=0.0001))
print('Newton:',optimize.newton(y,5,fprime=dy))
print('Secant:',optimize.newton(y,5))
print('Brent',optimize.brentq(y,-5,5))

Bisection: 1.2418365478515625
Newton: 1.2418965630344798
Secant: 1.2418965630344803
Brent 1.241896563034559


## general solver

In [78]:
import scipy.optimize as optimize
y=lambda x:x**3+2*x**2-5
dy=lambda x:3*x**2+4*x
print(optimize.fsolve(y,5,fprime=dy))

[1.24189656]


In [79]:
print(optimize.root(y,5))

    fjac: array([[-1.]])
     fun: array([3.55271368e-15])
 message: 'The solution converged.'
    nfev: 12
     qtf: array([-3.73605502e-09])
       r: array([-9.59451815])
  status: 1
 success: True
       x: array([1.24189656])


In [80]:
print(optimize.fsolve(y,-5,fprime=dy))

[-1.33306553]


C:\Users\16469\anaconda3\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


In [81]:
print(optimize.root(y,-5))

    fjac: array([[-1.]])
     fun: array([-3.81481496])
 message: 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.'
    nfev: 28
     qtf: array([3.81481521])
       r: array([-0.00461503])
  status: 5
 success: False
       x: array([-1.33306551])
